# Generated by Django 5.1.2 on 2024-11-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_contratacion', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cronica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dosis_recomendada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('habitacion', models.CharField(max_length=10, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('resuelto', models.BooleanField(default=False)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.residente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.empleado')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.residente')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenteEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField()),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.enfermedad')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.residente')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DioxWeb.rol'),
        ),
        migrations.CreateModel(
            name='ResidenteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.medicamento')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DioxWeb.residente')),
            ],
            options={
                'unique_together': {('residente', 'medicamento', 'fecha_inicio')},
            },
        ),
    ]
