# Generated by Django 5.1.2 on 2024-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DioxWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/empleados/'),
        ),
        migrations.AddField(
            model_name='residente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/residentes/'),
        ),
    ]
