# Generated by Django 5.1.2 on 2024-11-18 21:31

import DioxWeb.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DioxWeb', '0002_empleado_imagen_residente_imagen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residentemedicamento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cuidado',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='residente',
            name='dni',
        ),
        migrations.AddField(
            model_name='cuidado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuidado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='11111111-1', max_length=12, unique=True, validators=[DioxWeb.models.validar_rut]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='rut',
            field=models.CharField(default='11111111-1', max_length=12, unique=True, validators=[DioxWeb.models.validar_rut]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentemedicamento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentemedicamento',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='residentemedicamento',
            constraint=models.UniqueConstraint(fields=('residente', 'medicamento', 'fecha_inicio'), name='unique_residente_medicamento'),
        ),
    ]
