# Generated by Django 5.1.2 on 2024-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DioxWeb', '0003_alter_residentemedicamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='residentes/'),
        ),
    ]
