# Generated by Django 5.1.2 on 2024-11-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DioxWeb', '0004_alter_residente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residenteenfermedad',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='DioxWeb.residente'),
        ),
    ]
