# Generated by Django 5.1.2 on 2024-11-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DioxWeb', '0005_alter_residenteenfermedad_residente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='habitacion',
            field=models.CharField(max_length=10),
        ),
    ]
