# Generated by Django 5.1.2 on 2024-11-20 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DioxWeb', '0006_alter_residente_habitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analgesico',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('opioide', 'Opioide'), ('no_opioide', 'No Opioide')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Ansiolitico',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('clasificacion', models.CharField(choices=[('benzodiazepinas', 'Benzodiazepinas'), ('no_benzodiazepinas', 'No Benzodiazepinas')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antialergico',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('antihistaminico', 'Antihistamínico'), ('corticosteroide', 'Corticosteroide'), ('leucotrieno', 'Antagonista de Leucotrienos')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antibiotico',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('clase', models.CharField(choices=[('penicilina', 'Penicilina'), ('cefalosporina', 'Cefalosporina'), ('macrolidos', 'Macrólidos'), ('quinolonas', 'Quinolonas')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Anticonceptivo',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('oral', 'Oral'), ('inyectable', 'Inyectable'), ('implante', 'Implante'), ('condon', 'Condón')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antidepresivo',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('clasificacion', models.CharField(choices=[('ISRS', 'Inhibidores selectivos de la recaptación de serotonina'), ('IRSN', 'Inhibidores de la recaptación de serotonina y noradrenalina')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antidiabetico',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('insulina', 'Insulina'), ('biguanidas', 'Biguanidas'), ('sulfonilureas', 'Sulfonilureas')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antihipertensivo',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('clase', models.CharField(choices=[('IECA', 'Inhibidores de la Enzima Convertidora de Angiotensina'), ('ARA', 'Antagonistas de los Receptores de Angiotensina'), ('diuretico', 'Diurético'), ('beta_bloqueante', 'Beta-bloqueante')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antiinflamatorio',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('esteroide', 'Esteroide'), ('no_esteroide', 'No Esteroide')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Antipsicotico',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('atipico', 'Atípico'), ('tipico', 'Típico')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Estimulante',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('clasificacion', models.CharField(choices=[('anfetamina', 'Anfetamina'), ('metilfenidato', 'Metilfenidato')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Laxante',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('tipo', models.CharField(choices=[('irritante', 'Irritante'), ('formador_de_masa', 'Formador de Masa'), ('lubricante', 'Lubricante')], max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('medicamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DioxWeb.medicamento')),
                ('enfermedad_previene', models.CharField(max_length=100)),
            ],
            bases=('DioxWeb.medicamento',),
        ),
    ]
